# Generated by Django 4.0 on 2021-12-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=80)),
                ('startingtime', models.CharField(max_length=10)),
                ('endingtime', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=0)),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=70)),
                ('time_interval', models.TextField()),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
