# Generated by Django 4.0 on 2022-01-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20211231_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('WDEVELOPMENT', 'WDEVELOPMENT'), ('ADEVELOPMENT', 'ADEVELOPMENT'), ('MUSIC', 'MUSIC'), ('MANIPULATION', 'MANIPULATION')], max_length=80, null=True),
        ),
    ]
