# Generated by Django 4.0 on 2022-01-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_experience_company_alter_education_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
