# Generated by Django 4.0 on 2022-01-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_experience_link_alter_project_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('author', models.CharField(max_length=50)),
                ('intro_part', models.TextField()),
                ('body', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='uploads/admin/')),
            ],
        ),
    ]
