# Generated by Django 4.0 on 2022-01-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_blogs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Blog',
        ),
    ]
