# Generated by Django 4.0 on 2022-01-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_blog_author_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author_pic',
            field=models.ImageField(default='pictures/mah.jpg', null=True, upload_to='pictures/'),
        ),
    ]
