# Generated by Django 4.0 on 2022-01-29 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_alter_blog_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='intro_part',
        ),
    ]
