# Generated by Django 4.1.1 on 2022-09-30 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author_pic',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
    ]
