# Generated by Django 4.1.1 on 2022-09-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_remove_blog_author_pic_remove_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/admin/'),
        ),
    ]
