# Generated by Django 4.1.1 on 2022-10-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_entry',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
