# Generated by Django 4.1.1 on 2023-04-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_project_source_code_project_view_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='icons'),
        ),
    ]
