# Generated by Django 4.1.1 on 2023-09-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_bio_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(blank=True, max_length=80)),
                ('skill_image', models.ImageField(blank=True, null=True, upload_to='icons/skills')),
            ],
        ),
        migrations.AddField(
            model_name='bio',
            name='about_me_image',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
        migrations.AddField(
            model_name='bio',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Website', 'Website'), ('MOBILE APP', 'MOBILE APP'), ('ART', 'ART')], max_length=80, null=True),
        ),
    ]
