# Generated by Django 4.1.1 on 2023-09-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_skill_bio_about_me_image_bio_front_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='pinterest',
            field=models.URLField(blank=True, null=True),
        ),
    ]
