# Generated by Django 4.1.1 on 2023-09-21 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_bio_facebook_bio_github_bio_instagram_bio_pinterest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bio',
            old_name='facebook',
            new_name='linkedin',
        ),
    ]
