# Generated by Django 4.1.1 on 2024-03-13 04:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_rename_facebook_bio_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'png', 'svg'])]),
        ),
    ]
