# Generated by Django 4.1.1 on 2024-05-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
