# Generated by Django 5.2.8 on 2025-11-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_bio_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
